---
site_name: TekHSI
repo_url: https://github.com/tektronix/TekHSI
edit_uri: ''
site_author: Tektronix
site_description: Transfer waveforms from Tektronix Oscilloscopes using the High-Speed
  Interface
copyright: Â© Copyright 2022, Tektronix
strict: true
site_url: !ENV [READTHEDOCS_CANONICAL_URL, null]
use_directory_urls: true
exclude_docs: |
  *.py
  *.txt
  _templates/
  includes/
  __*/
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  not_found: warn
  anchors: warn
theme:
  name: readthedocs
  analytics:
    gtag: G-SDPEX4WBKJ
  highlightjs: false
  custom_dir: docs/_templates/readthedocs
  include_homepage_in_sidebar: false
  titles_only: false
  navigation_depth: 20
  collapse_navigation: true
  sticky_navigation: true
  features: [content.tooltips]
extra_css:
  - _static/css/api_labels.css
  - _static/css/api_symbols.css
  - _static/css/code_styles.css
  - _static/css/theme_overrides.css
  - _static/css/copybutton.css
extra_javascript:
  - _static/js/insert-hr.js
  - _static/js/clipboard.min.js
  - _static/js/copybutton.js
markdown_extensions:
  - meta
  - toc:
      permalink: true
  - tables
  - fenced_code
  - abbr
  - smarty
  - admonition
  - footnotes
  - md_in_html
  - sane_lists
  - attr_list
  - def_list
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: default
      pygments_lang_class: true
      code_attr_on_pre: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
plugins:
  - search:
      prebuild_index: true
  - include-markdown
  - section-index
  - autorefs
  - macros:
      module_name: docs/macros
      on_error_fail: true
      on_undefined: strict
  - gen-files:
      scripts: [docs/generate_api_pages.py]
  - literate-nav
  - ezglossary:
      tooltip: full
      strict: true
      use_default: true
      inline_refs: none
      markdown_links: true
  - mermaid2:
      javascript: https://cdnjs.cloudflare.com/ajax/libs/mermaid/11.3.0/mermaid.min.js
  - mkdocstrings:  # additional customization takes place in docs/generate_api_pages.py
      enable_inventory: true
      custom_templates: docs/_templates/mkdocstrings
      handlers:
        python:  # see https://mkdocstrings.github.io/python/usage/
          paths: [src]
          options:
            # General options
            inheritance_diagram_direction: LR
            show_inheritance_diagram: true
            show_source: false  # a link is included at the top of each page
            # Headings options
            heading_level: 1
            show_root_heading: true
            show_root_full_path: false
            show_category_heading: false
            show_symbol_type_heading: true
            show_symbol_type_toc: false
            # Members options
            inherited_members: true
            members_order: alphabetical
            filters: ['!^_', ^__init__]
            summary: false  # Currently implemented with custom templates
            show_labels: true
            # Docstrings options
            docstring_options:
              ignore_init_summary: true
              trim_doctest_flags: true
            docstring_section_style: list
            merge_init_into_class: true
            relative_crossrefs: true
            scoped_crossrefs: true
            # Signature options
            line_length: 100
            modernize_annotations: false  # if the source code annotations format changes, update this to true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            unwrap_annotated: true
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
            - url: https://typing-extensions.readthedocs.io/en/stable/objects.inv
              domains: [std, py]
            - url: https://pyvisa.readthedocs.io/en/stable/objects.inv
              domains: [std, py]
            - url: https://packaging.pypa.io/en/stable/objects.inv
              domains: [std, py]
            - url: https://requests.readthedocs.io/en/stable/objects.inv
              domains: [std, py]
            - url: https://tm-data-types.readthedocs.io/stable/objects.inv
              domains: [std, py]
  - spellcheck:
      known_words: known_words.txt
      skip_files: [CHANGELOG.md, reference/*]
      backends:
        - symspellpy
        - codespell:
            dictionaries:
              - clear
              - rare
              - informal
              - usage
              - code
              - names
              - en-GB_to_en-US
      ignore_code: true
      min_length: 2
      max_capital: 1
      allow_unicode: true
      strict_only: true
nav:  # The first entry in each section needs a hard-coded title to avoid being folded in as the section index
  - index.md
  - The Basics:
      - Basic Usage: basic_usage.md
      - glossary.md
      - CHANGELOG.md
  - Contributing:
      - Contributing Guidelines: CONTRIBUTING.md
      - CODE_OF_CONDUCT.md
      - LICENSE.md
  - API Reference: reference/
